-- MySQL Script generated by MySQL Workbench
-- Mon Nov 26 17:46:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_freeboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_freeboard` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `writer` VARCHAR(45) NOT NULL,
  `content` VARCHAR(255) NULL,
  `view_cnt` INT NULL,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_freeboard_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_freeboard_file` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `board_no` INT NULL,
  `file_ori_name` VARCHAR(45) NULL,
  `file_save_name` VARCHAR(45) NULL,
  `file_size` INT NULL,
  PRIMARY KEY (`no`),
  INDEX `no_idx` (`board_no` ASC) VISIBLE,
  CONSTRAINT `no`
    FOREIGN KEY (`board_no`)
    REFERENCES `mydb`.`t_freeboard` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ex_reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ex_reply` (
  `reply_no` INT NOT NULL,
  `board_no` INT NULL,
  `id` VARCHAR(45) NULL,
  `reply_content` VARCHAR(100) NULL,
  `reply_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `info` VARCHAR(100) NULL,
  PRIMARY KEY (`reply_no`),
  INDEX `no_idx` (`board_no` ASC) VISIBLE,
  CONSTRAINT `no`
    FOREIGN KEY (`board_no`)
    REFERENCES `mydb`.`t_freeboard` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_like` (
  `like_no` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(45) NULL,
  `pName` VARCHAR(45) NULL,
  `pIntro` VARCHAR(255) NULL,
  `title` VARCHAR(100) NULL,
  `t_likecol` VARCHAR(45) NULL,
  PRIMARY KEY (`like_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_like_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_like_file` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `like_no` INT NULL,
  `oriname` VARCHAR(45) NULL,
  `savename` VARCHAR(45) NULL,
  `fsize` INT NULL,
  PRIMARY KEY (`no`),
  INDEX `like_no_idx` (`like_no` ASC) VISIBLE,
  CONSTRAINT `like_no`
    FOREIGN KEY (`like_no`)
    REFERENCES `mydb`.`t_like` (`like_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_like_reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_like_reply` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `like_no` INT NULL,
  `info` VARCHAR(45) NULL,
  `id` VARCHAR(45) NULL,
  `content` VARCHAR(255) NULL,
  `nickname` VARCHAR(45) NULL,
  PRIMARY KEY (`no`),
  INDEX `like_no_idx` (`like_no` ASC) VISIBLE,
  CONSTRAINT `like_no`
    FOREIGN KEY (`like_no`)
    REFERENCES `mydb`.`t_like` (`like_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_member` (
  `id` VARCHAR(45) NOT NULL,
  `t_membercol` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NULL,
  `petNo` INT NULL,
  `tel` VARCHAR(45) NULL,
  `basic_addr` VARCHAR(45) NULL,
  `type` VARCHAR(5) NULL,
  `reg_date` DATETIME NULL DEFAULT current_timestamp,
  `point` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_member_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_member_file` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `memberId` VARCHAR(45) NULL,
  `fileOriName` VARCHAR(45) NULL,
  `fileSaveName` VARCHAR(45) NULL,
  `fileSize` VARCHAR(45) NULL,
  `t_member_filecol` INT NULL,
  PRIMARY KEY (`no`),
  INDEX `id_idx` (`memberId` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`memberId`)
    REFERENCES `mydb`.`t_member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_pet` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `owner` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `age` INT NULL,
  `sex` VARCHAR(10) NULL,
  `species` VARCHAR(45) NULL,
  PRIMARY KEY (`no`),
  INDEX `id_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`owner`)
    REFERENCES `mydb`.`t_member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
